server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: TIM.2@GMAIL.COM
    url: jdbc:mysql://localhost:3306/timmy?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: timothymasailelo@gmail.com
    password: awomdedtgxbczgzf

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
